# Feature Extractor:

* __input:__ problems.csv file (scraped and parsed data from [MoonBoard website](https://moonboard.com)

* __output:__ _problems_with_features.csv_ and _holds_with_features.csv_ files

In [1]:
import pandas as pd
import numpy as np
import ast

### problems.csv columns:

* __Name:__ _(from MoonBoard database, scraped data)_ name of the route 

* __Grade:__ _(from MoonBoard database, scraped data)_ difficulty grade of the route in Fontainebelau System

    Annotaion: Two bouldering grading system are avaible in MoonBoard app: Hueco(USA, V-scale) and Fontainebleau(French). 
Fontainebleau system is more precise than Hueco, i.e. there are more grade classes in Fontainebleau system. [Comparison Chart](https://99boulders.com/wp-content/uploads/2014/11/Bouldering-Grades-e1505766945353.jpg) 


* __Moves:__ _(from MoonBoard database, scraped data)_ Holds in a route. List of dictionaries. Dictionaries include holds' information in a route: 
    * Descripton -name of the hold(string), 
    * IsStart(boolean), 
    * IsEnd(boolean).
    * Id: NOTE: Id information is not consistent. ID's of the same hold in different problems are different.

* __Id:__ _(from MoonBoard database, scraped data)_ Id of the route.

### columns created in this jupyter notebook:


* __number_of_holds:__ number of holds in the problem


* __holds:__ list of holds in the route


* __lengths_of_moves:__ Lenghts of all possible moves in a route. Euclidean distances between all binary combinations of holds in the problem

---

### holds.csv columns:
holds dataframe will be initialized in this jupyter notebook

### columns created in this jupyter notebook:

holds dataframe will be initialized in this jupyter notebook

* __name:__ Name of the hold

* __grade_distribution:__ difficulty grade distribution of the hold in Fontainebelau System

* __color:__ The color of the hold - string

* __black:__ Binary - 0 or 1

* __white:__ Binary - 0 or 1

* __yellow:__ Binary - 0 or 1

* __force_z:__
    * ordinal: 0, 1 or 2. 
    * direction of force at z: 
    * Can one grip the hold and apply force at Z direction (outwards, perpendicular to the wall)
    * it indirectly gives an idea of a hold's incut size(larger incut size, easier to grip, so easier route) 

* __rotational_angle:__ Rotational angle of the hold
    * (categorical) 
    What I mean by rotational angle of a hold is that in which direction one can apply force to a hold. For example, one can only apply force to hold A5 downwards, whereas you can apply force to hold E14 both leftwards and rightwards. I believe it will be useful information when we set conditions to decide transition through states
    * (*Mert will analyze moonboard and fill the column)

* __slopeness:__ (ordinal or binary) - Is hold slope in its rotational angle. Sloper holds are harder to grab. 
    * (*Mert will analyze moonboard and fill the column)

In [2]:
# problems
problems = pd.read_csv("problems.csv")

In [3]:
# converts Moves column cells' types from str to original list

# problems DataFrame
 # Moves column
problem_list = []
for problem in problems["Moves"].values:
    problem_as_lst = ast.literal_eval(problem)
    problem_list.append(problem_as_lst)
problems["Moves"] = problem_list
problems.drop(["Unnamed: 0"], axis=1, inplace=True)

In [4]:
problems

,Name,Grade,Moves,Holdsets,Id
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184
...,...,...,...,...,...
446,JUST ANOTHER DAY,6C,"[{'Id': 1555486, 'Description': 'F5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",125131
447,LE UOVA SODE,6C,"[{'Id': 1680083, 'Description': 'E13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",274947
448,LOW CARB VAR,6C,"[{'Id': 1527581, 'Description': 'K5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set A', 'Color...",39242
449,MAFFEI,6C,"[{'Id': 1523127, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set B', 'Color...",27102
450,MOON CASTLE,6C,"[{'Id': 1844732, 'Description': 'B13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",196769

## route feature extractor

In [5]:
# feature 1: number of holds
# extracts number of holds in route and write it into column "Number of Holds"

def holds_of_problems(DataFrame):
    holdsColumn = []
    for i in range(DataFrame.shape[0]): 
        moves = DataFrame.loc[i]["Moves"]
        holdsList = []
        for move in moves:
            holdsList.append(move["Description"])
        holdsColumn.append(holdsList)
    DataFrame["holds"] = holdsColumn
    return DataFrame

def number_of_holds(DataFrame):
    number_of_holds = []
    for problem in DataFrame["Moves"].values:
        number_of_holds.append(len(problem))
    DataFrame["number_of_holds"] = number_of_holds
    return DataFrame


holds_of_problems(problems)
number_of_holds(problems)

problems.head()

,Name,Grade,Moves,Holdsets,Id,holds,number_of_holds
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224,"[J5, I9, E14, H18]",4
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575,"[K6, K7, D10, H14, A16, A18]",6
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045,"[D3, B4, G7, I8, K12, H14, H15, C18]",8
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783,"[E6, G2, J6, F8, J12, F15, F16, A18]",8
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184,"[B4, G7, H7, K8, K10, K13, G16, H18]",8

In [6]:
# feature 2
# lengths of all possible moves

# list of alphabet
alphabet = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]

# returns euclidean distance between two holds:
def eucl_dist(hold1, hold2):
    # hold1 as numpy array
    x_coord = alphabet.index(hold1[0].upper())
    y_coord = int(hold1[1:])
    hold1_tuple = tuple((x_coord, y_coord))
    hold1 = np.array(hold1_tuple)
    
    # hold2 as numpy array
    x_coord = alphabet.index(hold2[0].upper())
    y_coord = int(hold2[1:])
    hold2_tuple = tuple((x_coord, y_coord))  
    hold2 = np.array(hold2_tuple)  
    
    # distance
    dist = np.linalg.norm(hold1-hold2)
    
    return dist


def lengths_of_moves(DataFrame):
    listOfLenDicts = []
    for i in range(DataFrame.shape[0]):  
        holds = DataFrame.loc[i]["holds"]
        lenDict = {}
        for hold1 in holds:
            for hold2 in holds:
                lenDict[hold1 + "to" + hold2] = eucl_dist(hold1, hold2)
        listOfLenDicts.append(lenDict)
    DataFrame["lengths_of_moves"] = listOfLenDicts
    return DataFrame


lengths_of_moves(problems)

,Name,Grade,Moves,Holdsets,Id,holds,number_of_holds,lengths_of_moves
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224,"[J5, I9, E14, H18]",4,"{'J5toJ5': 0.0, 'J5toI9': 4.123105625617661, '..."
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575,"[K6, K7, D10, H14, A16, A18]",6,"{'K6toK6': 0.0, 'K6toK7': 1.0, 'K6toD10': 8.06..."
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045,"[D3, B4, G7, I8, K12, H14, H15, C18]",8,"{'D3toD3': 0.0, 'D3toB4': 2.23606797749979, 'D..."
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783,"[E6, G2, J6, F8, J12, F15, F16, A18]",8,"{'E6toE6': 0.0, 'E6toG2': 4.47213595499958, 'E..."
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184,"[B4, G7, H7, K8, K10, K13, G16, H18]",8,"{'B4toB4': 0.0, 'B4toG7': 5.830951894845301, '..."
...,...,...,...,...,...,...,...,...
446,JUST ANOTHER DAY,6C,"[{'Id': 1555486, 'Description': 'F5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",125131,"[F5, J5, J8, K11, I12, I14, E15, E18]",8,"{'F5toF5': 0.0, 'F5toJ5': 4.0, 'F5toJ8': 5.0, ..."
447,LE UOVA SODE,6C,"[{'Id': 1680083, 'Description': 'E13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",274947,"[E13, F5, G18, I10, I12, I14, J8]",7,"{'E13toE13': 0.0, 'E13toF5': 8.06225774829855,..."
448,LOW CARB VAR,6C,"[{'Id': 1527581, 'Description': 'K5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set A', 'Color...",39242,"[K5, G8, D9, H11, E13, B16, E18]",7,"{'K5toK5': 0.0, 'K5toG8': 5.0, 'K5toD9': 8.062..."
449,MAFFEI,6C,"[{'Id': 1523127, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set B', 'Color...",27102,"[J5, E12, A14, E8, D18]",5,"{'J5toJ5': 0.0, 'J5toE12': 8.602325267042627, ..."
450,MOON CASTLE,6C,"[{'Id': 1844732, 'Description': 'B13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",196769,"[B13, D18, D10, E12, E16, G9, I5, K5]",8,"{'B13toB13': 0.0, 'B13toD18': 5.38516480713450..."

In [7]:
# feature 3
# holds grade distribution of a problem

# Ã¶nce her hold'un difficulty daÄŸÄ±lÄ±mÄ±nÄ± elde et
# sonra rotadaki tutamaklarÄ±n mean difficulty daÄŸÄ±lÄ±mlarÄ±nÄ±n mean difficulty'sini elde et



# hold set
def holdSet(DataFrame):
    holdSet = set()
    for moves in problems["Moves"]:
        for move in moves:
            holdSet.add(move["Description"])
    holdSet.add("H13")
    holdSet.remove("j5")
    holdSet.add("J5")
    return holdSet


# input hold
# returns tuple:
# hold grade tuple: ("nameOfTheHold": {"6B+": numberOfRoutes, "6C+":,})
# tuple (string, dictionary)
# string = nameOfTheHold
# dictionary = empyty grade distribution of the hold

def holdTuple(hold):
    return (hold, {"6B+": 0, "6C":0, "6C+":0, "7A":0, "7A+":0, "7B":0,"7B+":0, "7C":0, "7C+":0, "8A":0, "8A+":0, "8B":0})



def holdGradeDistribution(hold, DataFrame):
    holdGrades = holdTuple(hold)
    for i in range(len(DataFrame)):
        problem = DataFrame.loc[i]
        if hold in problem["holds"]:
            holdGrades[1][problem["Grade"]] += 1
    return holdGrades

In [8]:
problems

,Name,Grade,Moves,Holdsets,Id,holds,number_of_holds,lengths_of_moves
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224,"[J5, I9, E14, H18]",4,"{'J5toJ5': 0.0, 'J5toI9': 4.123105625617661, '..."
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575,"[K6, K7, D10, H14, A16, A18]",6,"{'K6toK6': 0.0, 'K6toK7': 1.0, 'K6toD10': 8.06..."
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045,"[D3, B4, G7, I8, K12, H14, H15, C18]",8,"{'D3toD3': 0.0, 'D3toB4': 2.23606797749979, 'D..."
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783,"[E6, G2, J6, F8, J12, F15, F16, A18]",8,"{'E6toE6': 0.0, 'E6toG2': 4.47213595499958, 'E..."
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184,"[B4, G7, H7, K8, K10, K13, G16, H18]",8,"{'B4toB4': 0.0, 'B4toG7': 5.830951894845301, '..."
...,...,...,...,...,...,...,...,...
446,JUST ANOTHER DAY,6C,"[{'Id': 1555486, 'Description': 'F5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",125131,"[F5, J5, J8, K11, I12, I14, E15, E18]",8,"{'F5toF5': 0.0, 'F5toJ5': 4.0, 'F5toJ8': 5.0, ..."
447,LE UOVA SODE,6C,"[{'Id': 1680083, 'Description': 'E13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",274947,"[E13, F5, G18, I10, I12, I14, J8]",7,"{'E13toE13': 0.0, 'E13toF5': 8.06225774829855,..."
448,LOW CARB VAR,6C,"[{'Id': 1527581, 'Description': 'K5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set A', 'Color...",39242,"[K5, G8, D9, H11, E13, B16, E18]",7,"{'K5toK5': 0.0, 'K5toG8': 5.0, 'K5toD9': 8.062..."
449,MAFFEI,6C,"[{'Id': 1523127, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set B', 'Color...",27102,"[J5, E12, A14, E8, D18]",5,"{'J5toJ5': 0.0, 'J5toE12': 8.602325267042627, ..."
450,MOON CASTLE,6C,"[{'Id': 1844732, 'Description': 'B13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",196769,"[B13, D18, D10, E12, E16, G9, I5, K5]",8,"{'B13toB13': 0.0, 'B13toD18': 5.38516480713450..."

In [9]:
# feature 4 
# move length ile hold difficulty arasÄ±nda bir iliÅŸki kur.

## hold feature extractor

In [10]:
# define hold DataFrame
# first sorts holds (holds data taken from raw problems dataframe)
# then define holds DataFrame


# hold set
# input dataframe
# return holdSet
def holdSet(DataFrame):
    holdSet = set()
    for moves in problems["Moves"]:
        for move in moves:
            holdSet.add(move["Description"])
    holdSet.add("H13")
    holdSet.remove("j5")
    holdSet.add("J5")
    return holdSet



# holdListSorter
# input DataFrame
# return sorted hold list: sortedHoldList

def holdListSorter(problems):
    sortedHoldList = []
    
    holdList = sorted(list(holdSet(problems)))

    
    holdsClassified = [[], [], [], [], [], [], [], [], [], [], []]
    

    for hold in holdList:
        if hold[0] == "A":
            holdsClassified[0].append(int(hold[1:]))
        elif hold[0] == "B":
            holdsClassified[1].append(int(hold[1:]))
        elif hold[0] == "C":
            holdsClassified[2].append(int(hold[1:]))
        elif hold[0] == "D":
            holdsClassified[3].append(int(hold[1:]))
        elif hold[0] == "E":
            holdsClassified[4].append(int(hold[1:]))
        elif hold[0] == "F":
            holdsClassified[5].append(int(hold[1:]))
        elif hold[0] == "G":
            holdsClassified[6].append(int(hold[1:]))
        elif hold[0] == "H":
            holdsClassified[7].append(int(hold[1:]))
        elif hold[0] == "I":
            holdsClassified[8].append(int(hold[1:]))
        elif hold[0] == "J":
            holdsClassified[9].append(int(hold[1:]))
        elif hold[0] == "K":
            holdsClassified[10].append(int(hold[1:]))

    
    holdsClassifiedSorted = []
    
    for holdList in holdsClassified:
        holdsClassifiedSorted.append(sorted(holdList))
    

    counter = 0
    for lst in holdsClassifiedSorted:
        for holdNumber in lst:
            if counter == 0:
                sortedHoldList.append("A" + str(holdNumber))
            elif counter == 1:
                sortedHoldList.append("B" + str(holdNumber))
            elif counter == 2:
                sortedHoldList.append("C" + str(holdNumber))
            elif counter == 3:
                sortedHoldList.append("D" + str(holdNumber))
            elif counter == 4:
                sortedHoldList.append("E" + str(holdNumber))
            elif counter == 5:
                sortedHoldList.append("F" + str(holdNumber))
            elif counter == 6:
                sortedHoldList.append("G" + str(holdNumber))
            elif counter == 7:
                sortedHoldList.append("H" + str(holdNumber))
            elif counter == 8:
                sortedHoldList.append("I" + str(holdNumber))
            elif counter == 9:
                sortedHoldList.append("J" + str(holdNumber))
            elif counter == 10:
                sortedHoldList.append("K" + str(holdNumber))
        counter += 1

    
    return sortedHoldList                    




# holds DataFrame

sortedHoldDict = {"name":[]}
sortedHoldDict["name"] = holdListSorter(problems)

holds = pd.DataFrame(sortedHoldDict)

In [11]:
# feature 1
# grade distribution of hold


# ------------------------ #

# holdTuple
# input hold
# returns tuple:
# hold grade tuple: ("nameOfTheHold": {"6B+": numberOfRoutes, "6C+":,})
# tuple (string, dictionary)
# string = nameOfTheHold
# dictionary = empyty grade distribution of the hold

def holdTuple(hold):
    return (hold, {"6B+": 0, "6C":0, "6C+":0, "7A":0, "7A+":0, "7B":0,"7B+":0, "7C":0, "7C+":0, "8A":0, "8A+":0, "8B":0})

# ------------------------ #

# holdGradeDistribution
# input hold, DataFrame
# return holdGrades tuple
# "F5", {"6B+": 0, "6C":0, "6C+":0, "7A":0, "7A+":0, "7B":0,"7B+":0, "7C":0, "7C+":0, "8A":0, "8A+":0, "8B":0}

def holdGradeDistribution(hold, DataFrame):
    holdGrades = holdTuple(hold)
    for i in range(len(DataFrame)):
        problem = DataFrame.loc[i]
        if hold in problem["holds"]:
            holdGrades[1][problem["Grade"]] += 1
    return holdGrades


# input holds dataframe
# return dataframe with grade distribution column

def gradeDistributionFeature(holds):
    holdsGradeDistributionList = []
    
    for i in range(len(holds)):
        hold = holds.loc[i]["name"]
        gradeDistribution = holdGradeDistribution(hold, problems)
        
        holdsGradeDistributionList.append(gradeDistribution[1])
    
    holds["grade_distribution"] = holdsGradeDistributionList
    
    return holds

holds = gradeDistributionFeature(holds)

In [12]:
# feature 2
# hold color

# column Colors: string
# columns; black: 0, 1; white: 0, 1; yellow: 0, 1  


holdColorDictionary = {'A5':"white", 'A9':"black", 'A10':"yellow", 'A11':"yellow", 'A12':"white", 'A13':"yellow", 'A14':"black", 'A15':"white", 'A16':"yellow", 'A18':"black", 'B3':"white", 'B4':"yellow", 'B6':"black", 'B7':"yellow", 'B8':"white", 'B9':"white", 'B10':"black", 'B11':"white", 'B12':"black", 'B13':"white", 'B15':"black", 'B16':"white", 'B18':"white", 'C5':"black", 'C6':"white", 'C7':"yellow", 'C8':"black", 'C9':"yellow", 'C10':"white", 'C11':"white", 'C12':"yellow", 'C13':"black", 'C14':"white", 'C15':"yellow", 'C16':"black", 'C18':"yellow", 'D3':"yellow", 'D5':"white", 'D6':"yellow", 'D7':"black", 'D8':"yellow", 'D9':"white", 'D10':"yellow", 'D11':"black", 'D12':"white", 'D13':"yellow", 'D14':"white", 'D15':"black", 'D16':"yellow", 'D17':"white", 'D18':"black", 'E6':"black", 'E7':"white", 'E8':"black", 'E9':"black", 'E10':"white", 'E11':"white", 'E12':"black", 'E13':"white", 'E14':"black", 'E15':"white", 'E16':"black", 'E18':"white", 'F5':"white", 'F6':"yellow", 'F7':"white", 'F8':"yellow", 'F9':"yellow", 'F10':"white", 'F11':"black", 'F12':"white", 'F13':"black", 'F14':"white", 'F15':"yellow", 'F16':"white", 'G2':"white", 'G4':"black", 'G6':"black", 'G7':"yellow", 'G8':"white", 'G9':"black", 'G10':"black", 'G11':"yellow", 'G12':"white", 'G13':"white", 'G14':"black", 'G15':"black", 'G16':"yellow", 'G17':"black", 'G18':"white", 'H5':"black", 'H7':"yellow", 'H8':"black", 'H9':"yellow", 'H10':"black", 'H11':"white", 'H12':"black", 'H13':"black", 'H14':"yellow", 'H15':"yellow", 'H16':"black", 'H18':"yellow", 'I4':"white", 'I5':"yellow", 'I6':"white", 'I7':"black", 'I8':"yellow", 'I9':"black", 'I10':"black", 'I11':"white", 'I12':"yellow", 'I13':"white", 'I14':"black", 'I15':"black", 'I16':"white", 'I18':"black", 'J2':"white", 'J5':"black", 'J6':"white", 'J7':"black", 'J8':"white", 'J9':"white", 'J10':"white", 'J11':"yellow", 'J12':"black", 'J13':"black", 'J14':"yellow", 'J16':"black", 'K5':"white", 'K6':"yellow", 'K7':"yellow", 'K8':"yellow", 'K9':"black", 'K10':"yellow", 'K11':"white", 'K12':"yellow", 'K13':"yellow", 'K14':"black", 'K16':"black", 'K18':"white"}


# adds Color column
# input holds dataframe
# return holds dataframe with column Color

def holdColor(holds):
    holdsColorList = []
    for i in range(len(holds)):
        hold = holds.iloc[i]
        holdsColorList.append(holdColorDictionary[hold["name"]])
    
    holds["color"] = holdsColorList
    
    return holds

holds = holdColor(holds)


# add 3 color columns
# black white yellow
# 0 or 1

def holdColorNumeric(holds):
    blackColorList = []
    whiteColorList = []
    yellowColorList = []
    
    for i in range(len(holds)):
        hold = holds.iloc[i]
        
        if hold["color"] == "black":
            blackColorList.append(1)
            whiteColorList.append(0)
            yellowColorList.append(0)  
        elif hold["color"] == "white":
            blackColorList.append(0)
            whiteColorList.append(1)
            yellowColorList.append(0)
        else:
            blackColorList.append(0)
            whiteColorList.append(0)
            yellowColorList.append(1)
            
    holds["black"] = blackColorList
    holds["white"] = whiteColorList
    holds["yellow"] = yellowColorList
    
    return holds

holds = holdColorNumeric(holds)

In [13]:
# feature 3

# ordinal: 0, 1 or 2. 
# direction of force at z: 
# Can one grip the hold and apply force at Z direction (outwards, perpendicular to the wall)
# it indirectly gives an idea of a hold's incut size(larger incut size, easier to grip, so easier route) 

hold_dict_z_ordinal = {'A5': 0,'A9': 1, 'A10': 0,'A11': 0,'A12': 0,'A13': 1,'A14': 2,'A15': 1,'A16': 1,'A18': 1,'B3': 2, 'B4': 1, 'B6': 1, 'B7': 0, 'B8': 1, 'B9': 1, 'B10': 2,'B11': 2,'B12': 0,'B13': 2,'B15': 0,'B16': 1,'B18': 2,'C5': 1, 'C6': 0, 'C7': 2, 'C8': 1, 'C9': 0, 'C10': 2,'C11': 0,'C12': 1,'C13': 2,'C14': 1,'C15': 2,'C16': 1,'C18': 1,'D3': 1,'5': 0,'D6': 0,'D7': 0,'D8': 0,'D9': 1,'D10': 2, 'D11': 2, 'D12': 2, 'D13': 2, 'D14': 0, 'D15': 2, 'D16': 0, 'D17': 1, 'D18': 2, 'E6': 1, 'E7': 1, 'E8': 1, 'E9': 0, 'E10': 2,'E11': 1,'E12': 2,'E13': 1,'E14': 2,'E15': 2,'E16': 2,'E18': 2,'F5': 2,'F6': 0,'F7': 1,'F8': 0,'F9': 1,'F10': 1,'F11': 1,'F12': 0,'F13': 1,'F14': 2,'F15': 1,'F16': 0,'G2': 2,'G4': 1,'G6': 2,'G7': 0,'G8': 1,'G9': 2,'G10': 1,'G11': 1,'G12': 1,'G13': 2,'G14': 1,'G15': 2,'G16': 0,'G17': 1,'G18': 2,'H5': 2,'H7': 0,'H8': 1,'H9': 2,'H10': 2,'H11': 2,'H12': 0,'H13': 2,'H14': 2,'H15': 0,'H16': 1,'H18': 1,'I4': 1,'I5': 2,'I6': 0,'I7': 0,'I8': 0,'I9': 2,'I10': 1,'I11': 1,'I12': 2,'I13': 0,'I14': 2,'I15': 1,'I16': 1,'I18': 2,'J2': 2,'J5': 2,'J6': 0,'J7': 1,'J8': 2,'J9': 2,'J10': 1,'J11': 0,'J12': 0,'J13': 2,'J14': 1,'J16': 1,'K5': 2,'6': 0,'K7': 0,'K8': 0,'K9': 2,'K10': 0,'K11': 2,'K12': 0,'K13': 0,'K14': 2,'K16': 1,'K18': 2}
holds["force_z"] = list(hold_dict_z_ordinal.values())

In [5]:
# feature 4
# rotational angle - categorical - (moonboard analyzed and feature added manually. check holds_with_features.csv file's rotational angle column). )

In [20]:
holds["rotational_angle"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
135   NaN
136   NaN
137   NaN
138   NaN
139   NaN
Name: rotational_angle, Length: 140, dtype: float64

In [15]:
# feature 5
# slopeness - (binary-categorical) - (analyze moonboard)

holds["slopeness"] = np.nan

In [16]:
holds

,name,grade_distribution,color,black,white,yellow,force_z,rotational_angle,slopeness
0,A5,"{'6B+': 5, '6C': 4, '6C+': 7, '7A': 9, '7A+': ...",white,0,1,0,0,NaN,NaN
1,A9,"{'6B+': 2, '6C': 4, '6C+': 1, '7A': 2, '7A+': ...",black,1,0,0,1,NaN,NaN
2,A10,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
3,A11,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
4,A12,"{'6B+': 0, '6C': 0, '6C+': 1, '7A': 1, '7A+': ...",white,0,1,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
135,K12,"{'6B+': 1, '6C': 1, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
136,K13,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
137,K14,"{'6B+': 0, '6C': 1, '6C+': 2, '7A': 0, '7A+': ...",black,1,0,0,2,NaN,NaN
138,K16,"{'6B+': 1, '6C': 1, '6C+': 0, '7A': 0, '7A+': ...",black,1,0,0,1,NaN,NaN
139,K18,"{'6B+': 5, '6C': 5, '6C+': 4, '7A': 4, '7A+': ...",white,0,1,0,2,NaN,NaN

In [17]:
problems

,Name,Grade,Moves,Holdsets,Id,holds,number_of_holds,lengths_of_moves
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224,"[J5, I9, E14, H18]",4,"{'J5toJ5': 0.0, 'J5toI9': 4.123105625617661, '..."
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575,"[K6, K7, D10, H14, A16, A18]",6,"{'K6toK6': 0.0, 'K6toK7': 1.0, 'K6toD10': 8.06..."
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045,"[D3, B4, G7, I8, K12, H14, H15, C18]",8,"{'D3toD3': 0.0, 'D3toB4': 2.23606797749979, 'D..."
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783,"[E6, G2, J6, F8, J12, F15, F16, A18]",8,"{'E6toE6': 0.0, 'E6toG2': 4.47213595499958, 'E..."
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184,"[B4, G7, H7, K8, K10, K13, G16, H18]",8,"{'B4toB4': 0.0, 'B4toG7': 5.830951894845301, '..."
...,...,...,...,...,...,...,...,...
446,JUST ANOTHER DAY,6C,"[{'Id': 1555486, 'Description': 'F5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",125131,"[F5, J5, J8, K11, I12, I14, E15, E18]",8,"{'F5toF5': 0.0, 'F5toJ5': 4.0, 'F5toJ8': 5.0, ..."
447,LE UOVA SODE,6C,"[{'Id': 1680083, 'Description': 'E13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",274947,"[E13, F5, G18, I10, I12, I14, J8]",7,"{'E13toE13': 0.0, 'E13toF5': 8.06225774829855,..."
448,LOW CARB VAR,6C,"[{'Id': 1527581, 'Description': 'K5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set A', 'Color...",39242,"[K5, G8, D9, H11, E13, B16, E18]",7,"{'K5toK5': 0.0, 'K5toG8': 5.0, 'K5toD9': 8.062..."
449,MAFFEI,6C,"[{'Id': 1523127, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set B', 'Color...",27102,"[J5, E12, A14, E8, D18]",5,"{'J5toJ5': 0.0, 'J5toE12': 8.602325267042627, ..."
450,MOON CASTLE,6C,"[{'Id': 1844732, 'Description': 'B13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",196769,"[B13, D18, D10, E12, E16, G9, I5, K5]",8,"{'B13toB13': 0.0, 'B13toD18': 5.38516480713450..."

In [18]:
# save

# problems.to_csv("problems_with_features.csv")
# holds.to_csv("holds_with_features.csv")